databases:
  - name: konnect-db
    databaseName: konnect
    user: konnect
    plan: free

services:
  - type: web
    name: konnect-inc
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn KONNECT_INC.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: konnect-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
